jobs:
    include:
      - language: python
        python:
        - "3.6"
        - "3.7"
        - "3.8"
        install: 
        - pip install -r back_end/requirements.txt
        script:
        - pytest back_end/
      
      - language: dart
        dist: xenial
        addons:
            apt:
                packages:
                    - lib32stdc++6
        install:
            - git clone https://github.com/flutter/flutter.git -b stable
            - ./flutter/bin/flutter doctor
            - gem install coveralls-lcov
        script:
            - cd mobile/
            - ../flutter/bin/flutter test --coverage test/
        after_success:            
            - coveralls-lcov ./coverage/lcov.info
        cache:
            directories:
            - $HOME/.pub-cache
