# Generated by Django 3.1.3 on 2020-11-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.SmallIntegerField(choices=[(0, 'teacher'), (1, 'professional'), (2, 'researcher')])),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
