# Generated by Django 3.1.3 on 2020-12-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='client_last_update',
        ),
    ]
