# Generated by Django 3.1.3 on 2020-11-27 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
