# Generated by Django 3.1.3 on 2020-12-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_class_client_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='client_last_update',
        ),
    ]
