# Generated by Django 3.1.3 on 2020-12-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_school_client_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='client_last_update',
        ),
        migrations.RemoveField(
            model_name='student',
            name='client_last_update',
        ),
        migrations.RemoveField(
            model_name='text',
            name='client_last_update',
        ),
    ]
