# Generated by Django 3.1.3 on 2020-11-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'teacher'), (1, 'professional'), (2, 'researcher')], default=0),
            preserve_default=False,
        ),
    ]
