# Generated by Django 3.1.3 on 2020-12-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201129_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='school',
        ),
    ]
